# version: '3'
# services:
#   app:
#     build: .
#     ports:
#       - "3000:3000"
version: '3.1'

services:
  websocket:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
      - "3002:3002"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:

